add session, user logic
SIBIRSKAYA-KORONA/sport4all-backend pull request #2
Opened 2021-02-06 17:39 UTC by TimRazumov

2021-02-08 14:01 UTC, chtvrv requested changes

2021-02-08 14:01 UTC, chtvrv commented on app/handlers/http/middleware.go
> +package http
Это чтобы отделить http-шные миддлвары от grpc-шных ?

2021-02-08 14:01 UTC, chtvrv commented on app/handlers/http/middleware.go
> +	SesUseCase useCases.SessionUseCase
SesUseCase немножко глаза режет, может не сокращать ?
И должно ли это поле быть публичным ?

2021-02-08 14:01 UTC, chtvrv commented on pkg/logger/logger.go
> +func InitLogger(logFile string, logLevelStr string) {
Окей, логгер не должен знать о viper, согласен

2021-02-08 14:01 UTC, chtvrv commented on app/server/server.go
> +	redisPool := &redis.Pool{
redigo подойдет нам я думаю полностью, популярная же либа, проблем не должно быть, так что ок я считаю

2021-02-08 14:01 UTC, chtvrv commented on app/server/server.go
> +				logger.Error(err.Error())
Не logger.Fatal ? Если postgreSQL не поднимается, то приложение падает, без рабочих сессий я думаю тоже нет смысла продолжать. Я сейчас просто кидал запросы, забыв редис поднять, а прога работала(

2021-02-08 14:01 UTC, chtvrv commented on app/server/settings.go
> +type Settings struct {
Сильно компактнее по сравнению с тем, что было у меня.
Тогда я закрывал протоколом. Думаю можно обойтись и без этого, но чтобы тогда не было проблем с тестами, будем просто прокидывать параметры из настроек в конструктор нуждающихся ? Например в миддлвару скоро нужно будет прокинуть адреса для CORS'а

2021-02-08 14:01 UTC, chtvrv commented on pkg/common/common.go
> +func Closed(closeFunc func() error) {
Думаю ок, удобненько, только по неймингу больше подойдет просто Close(), наверное, это же действие

2021-02-08 14:01 UTC, chtvrv commented on pkg/common/common.go
> +func SetCookie(ctx echo.Context, sid string, expires time.Time) {
Куками же будет заниматься только один сервис, имеет смысл выносить в общее ? Или же если у нас будет несколько кук, то параметр Name нужно вынести в аргумент функции

2021-02-08 14:01 UTC, chtvrv commented on pkg/hasher/password.go
> +func hash(salt []byte, password string) []byte {
Переиспользовано ведь из drello ? Тогда вроде проблем не было, и тут не должно возникнуть

2021-02-08 14:01 UTC, chtvrv commented on app/server/server.go
> +	// postgresClient.DropTableIfExists(&models.User{})
Для дэбага ? По идее можно в DataGrip чистить, если нужно. Это всё к вопросу dev окружения, тогда в drello мы вроде не запилили никакого тестового заполнения автоматического, возможно стоит в этот раз этим вопрос заняться

2021-02-08 14:01 UTC, chtvrv commented on app/repositories/psql/user.go
> +package psql
Прошлое название пакеты показалось слишком длинным ?
Ок, наверное, но возможно кто-то может спутаться с консольной утилитой

2021-02-08 14:01 UTC, chtvrv commented on app/handlers/http/session.go
> +func CreateSessionHandler(sessionURL string, router *echo.Group, useCase usecases.SessionUseCase, mw Middleware) {
Доку пока не стал писать ? Можем вместе попробовать

2021-02-08 14:01 UTC, chtvrv commented on app/models/user.go
> +	// example: 1234 (unix time)
(unix time) надо убрать, генерация доки ошибку выдает, потому что пытается спарсить всю строку в int64, аналогично в других полях

2021-02-08 14:01 UTC, chtvrv commented on app/server/server.go
> +	logger.Error("start server on address: ", server.settings.ServerAddress,
Это же не ошибка))

2021-02-08 14:07 UTC, TimRazumov commented on app/server/server.go
> +	logger.Error("start server on address: ", server.settings.ServerAddress,
всегда должен быть лог, сигнализирующий о старте сервиса. Error самый высокий уровень логгирования и обеспечивает, что лог напишется всегда

2021-02-08 14:07 UTC, TimRazumov commented on app/repositories/psql/user.go
> +package psql
да, показалось длинным. вряд ли кто-то перепутает

2021-02-08 14:08 UTC, TimRazumov commented on app/server/server.go
> +	// postgresClient.DropTableIfExists(&models.User{})
да, пускай пока будет. потом спилим

2021-02-08 14:10 UTC, TimRazumov commented on pkg/hasher/password.go
> +func hash(salt []byte, password string) []byte {
почти переиспользованно, немного поменял. концепция та же

2021-02-08 14:11 UTC, TimRazumov commented on app/server/server.go
> +				logger.Error(err.Error())
нет. тут используется redis pull, который держит пулл соединений и делает реконнекты. эта функция просто говорит этому пулу как надо реконнектиться

2021-02-08 14:11 UTC, TimRazumov commented on app/server/server.go
> +	redisPool := &redis.Pool{
ага

2021-02-08 14:11 UTC, TimRazumov commented on pkg/logger/logger.go
> +func InitLogger(logFile string, logLevelStr string) {
ага

2021-02-08 14:13 UTC, TimRazumov commented on app/handlers/http/middleware.go
> +	SesUseCase useCases.SessionUseCase
да, должен быть публичным для тестов. вообще была мысль разделить миддлвары. commonMW, UseCaseMW, NotifyMW. а то этот файл напоминает антипаттерн "божественный объект"

2021-02-08 14:13 UTC, TimRazumov commented on app/handlers/http/middleware.go
> +package http
ага

2021-02-08 14:13 UTC, TimRazumov commented on app/server/settings.go
> +type Settings struct {
да

2021-02-08 14:14 UTC, TimRazumov commented on pkg/common/common.go
> +func SetCookie(ctx echo.Context, sid string, expires time.Time) {
просто выставление куки достаточно громоздкая штука которая занимает много строчек копипастой и используется в 4-х местах. я решил вынести в отдельную функцию

2021-02-08 14:25 UTC, TimRazumov commented on app/repositories/psql/user.go
> +	"time"
тут надо поправить порядок либ

2021-02-12 17:38 UTC, TimRazumov commented on app/handlers/http/session.go
> +func CreateSessionHandler(sessionURL string, router *echo.Group, useCase usecases.SessionUseCase, mw Middleware) {
давай

2021-02-12 17:40 UTC, TimRazumov commented on app/repositories/psql/user.go
> +	"time"
done

2021-02-12 17:40 UTC, TimRazumov commented on app/models/user.go
> +	// example: 1234 (unix time)
убрал

2021-02-12 17:42 UTC, TimRazumov commented on pkg/common/common.go
> +func Closed(closeFunc func() error) {
переделал на Close

2021-02-12 17:42 UTC, TimRazumov commented on app/handlers/http/middleware.go
> +	SesUseCase useCases.SessionUseCase
сделал приватным

2021-02-12 19:41 UTC, merged